#!/bin/sh

# =====================
# = Customize me here =
# =====================

FAR_PATH="~/bin/far";
# Set to point to your far binary

# ========================
# = End of customization =
# ========================



# Fix DTerm current directory problem
cd "`dirname "$0"`"

# process skin far
far -m test-skin.xml
